from routes.acr import acr_bp
from routes.api_event_history import api_event_history_bp
from routes.bank import bank_bp
from routes.calendar import calendar_bp
from routes.google import google_bp
from routes.kubernetes import kubernetes_bp
from routes.location_history import location_history_bp
from routes.mongo_backup import mongo_backup_bp
from routes.podcasts import podcasts_bp
from routes.usage import usage_bp
from routes.weather import weather_bp
from routes.torrents import torrent_bp
from routes.redis import redis_bp
from routes.conversation import conversation_bp
from routes.android import android_bp
from routes.plaid import plaid_bp
from routes.ts import ts_bp
from routes.transcription import transcription_bp
